// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.Data.Migrations
{
    [DbContext(typeof(PostgresDbContext))]
    partial class PostgresDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API.Models.Course", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = "a945757a-fc5d-4558-a3f6-8716545ab954",
                            Name = "Angular"
                        },
                        new
                        {
                            Id = "befa383d-07d6-4b2b-aa57-8eea7132c4e5",
                            Name = "DotNet"
                        });
                });

            modelBuilder.Entity("API.Models.Lesson", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("SectionId")
                        .HasColumnType("text");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(355)
                        .HasColumnType("character varying(355)");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            Id = "5bf8757d-befc-478a-b140-f44047cd66e1",
                            Name = "Routing: Lesson 1",
                            Order = 0,
                            SectionId = "8c628339-02b3-4546-9e3f-a3dfbbfa564c",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "85b7ce46-f691-4f65-8f1e-a26059b31a45",
                            Name = "Routing: Lesson 2",
                            Order = 0,
                            SectionId = "8c628339-02b3-4546-9e3f-a3dfbbfa564c",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "1341ea73-1c77-46c6-be4f-ff8c40f299c7",
                            Name = "Routing: Lesson 3",
                            Order = 0,
                            SectionId = "8c628339-02b3-4546-9e3f-a3dfbbfa564c",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "75c0825b-f1de-497f-a289-fd339086f9ee",
                            Name = "Routing: Lesson 4",
                            Order = 0,
                            SectionId = "8c628339-02b3-4546-9e3f-a3dfbbfa564c",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "e5278d62-b6f5-44e5-b597-34d515e54ecb",
                            Name = "Routing: Lesson 5",
                            Order = 0,
                            SectionId = "8c628339-02b3-4546-9e3f-a3dfbbfa564c",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "efe69627-4e7d-4386-a9a8-f59a6e7a6a47",
                            Name = "Routing: Lesson 6",
                            Order = 0,
                            SectionId = "8c628339-02b3-4546-9e3f-a3dfbbfa564c",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "79cc9fe3-ae50-41ce-8fe1-eea369e5c07f",
                            Name = "Routing: Lesson 7",
                            Order = 0,
                            SectionId = "8c628339-02b3-4546-9e3f-a3dfbbfa564c",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "b340aa6a-8e79-4f37-8395-02771e42b234",
                            Name = "Routing: Lesson 8",
                            Order = 0,
                            SectionId = "8c628339-02b3-4546-9e3f-a3dfbbfa564c",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "67bbf005-a335-42ce-a8bd-6d91b8ccf376",
                            Name = "Routing: Lesson 9",
                            Order = 0,
                            SectionId = "8c628339-02b3-4546-9e3f-a3dfbbfa564c",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "a6bd99c6-6217-47f9-a80c-b996fa41f757",
                            Name = "Routing: Lesson 10",
                            Order = 0,
                            SectionId = "8c628339-02b3-4546-9e3f-a3dfbbfa564c",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "bbe2c99d-b182-461a-81cd-21a0d9e96142",
                            Name = "Service: Lesson 1",
                            Order = 0,
                            SectionId = "a5f742ec-af3b-41d7-b938-3f4c0de86b06",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "a115d6d8-a08a-45c1-93ea-52b41d888589",
                            Name = "Service: Lesson 2",
                            Order = 0,
                            SectionId = "a5f742ec-af3b-41d7-b938-3f4c0de86b06",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "6c17833a-e966-4a30-8948-c40b5ef924e9",
                            Name = "Service: Lesson 3",
                            Order = 0,
                            SectionId = "a5f742ec-af3b-41d7-b938-3f4c0de86b06",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "3a6991c2-4ea5-440c-9628-aba773941c1c",
                            Name = "Service: Lesson 4",
                            Order = 0,
                            SectionId = "a5f742ec-af3b-41d7-b938-3f4c0de86b06",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "0ebf02ad-413d-42d3-a28f-b2acfc93a2ca",
                            Name = "Service: Lesson 5",
                            Order = 0,
                            SectionId = "a5f742ec-af3b-41d7-b938-3f4c0de86b06",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "6e7b5881-8319-453e-9e0b-50d98e376bc5",
                            Name = "Service: Lesson 6",
                            Order = 0,
                            SectionId = "a5f742ec-af3b-41d7-b938-3f4c0de86b06",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "c146e570-bc2e-4189-820a-9025b64c27b5",
                            Name = "Service: Lesson 7",
                            Order = 0,
                            SectionId = "a5f742ec-af3b-41d7-b938-3f4c0de86b06",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "08975417-3eba-4c21-8a54-5b46be6a4574",
                            Name = "Service: Lesson 8",
                            Order = 0,
                            SectionId = "a5f742ec-af3b-41d7-b938-3f4c0de86b06",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "9a8fd836-c38c-4460-acaa-0f4eb5c81fad",
                            Name = "Service: Lesson 9",
                            Order = 0,
                            SectionId = "a5f742ec-af3b-41d7-b938-3f4c0de86b06",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "2d152c64-bfb5-42f3-a531-23902a2a60b2",
                            Name = "Service: Lesson 10",
                            Order = 0,
                            SectionId = "a5f742ec-af3b-41d7-b938-3f4c0de86b06",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "96f007ef-3063-4e35-9732-863c86bd1cb2",
                            Name = "Service: Lesson 11",
                            Order = 0,
                            SectionId = "a5f742ec-af3b-41d7-b938-3f4c0de86b06",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "991bebd9-5151-4a27-9390-ab860dc3e8c2",
                            Name = "Service: Lesson 12",
                            Order = 0,
                            SectionId = "a5f742ec-af3b-41d7-b938-3f4c0de86b06",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "bb9d597e-09a9-4ed5-8259-1aeed9c8e8b3",
                            Name = "Service: Lesson 13",
                            Order = 0,
                            SectionId = "a5f742ec-af3b-41d7-b938-3f4c0de86b06",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "f19b362d-6ec0-4cf8-9db8-833205bbc561",
                            Name = "Service: Lesson 14",
                            Order = 0,
                            SectionId = "a5f742ec-af3b-41d7-b938-3f4c0de86b06",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "b5dd0389-87eb-46f7-a499-5407af560321",
                            Name = "Service: Lesson 15",
                            Order = 0,
                            SectionId = "a5f742ec-af3b-41d7-b938-3f4c0de86b06",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "da619eac-3590-4eaf-9db7-dcaa6e8560fb",
                            Name = "Service: Lesson 16",
                            Order = 0,
                            SectionId = "a5f742ec-af3b-41d7-b938-3f4c0de86b06",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "233b21eb-8160-448e-9b14-14c556cf3a40",
                            Name = "Service: Lesson 17",
                            Order = 0,
                            SectionId = "a5f742ec-af3b-41d7-b938-3f4c0de86b06",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "f4d199c1-53e0-405b-b96e-cee437369e33",
                            Name = "Service: Lesson 18",
                            Order = 0,
                            SectionId = "a5f742ec-af3b-41d7-b938-3f4c0de86b06",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "d9332917-e901-4732-bb3b-361405403a4b",
                            Name = "Service: Lesson 19",
                            Order = 0,
                            SectionId = "a5f742ec-af3b-41d7-b938-3f4c0de86b06",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "53625b4d-858a-44d3-9716-a2c3fccb07da",
                            Name = "Service: Lesson 20",
                            Order = 0,
                            SectionId = "a5f742ec-af3b-41d7-b938-3f4c0de86b06",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "5929ff7c-31d1-42d8-8e8e-329b60e07c69",
                            Name = "Directive: Lesson 1",
                            Order = 0,
                            SectionId = "d5b9ad05-d155-4c74-baee-1c2eb15bc98b",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "828b5c4e-5d1c-49b4-b1a6-7b2470ee5e55",
                            Name = "Directive: Lesson 2",
                            Order = 0,
                            SectionId = "d5b9ad05-d155-4c74-baee-1c2eb15bc98b",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "b3867309-f262-4311-b52f-799b0e7477a3",
                            Name = "Directive: Lesson 3",
                            Order = 0,
                            SectionId = "d5b9ad05-d155-4c74-baee-1c2eb15bc98b",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "993ff438-e5c2-4ba9-bf17-b33c4559e9b8",
                            Name = "Directive: Lesson 4",
                            Order = 0,
                            SectionId = "d5b9ad05-d155-4c74-baee-1c2eb15bc98b",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "8036a483-b2ff-4610-a70c-ba1315492fc7",
                            Name = "Directive: Lesson 5",
                            Order = 0,
                            SectionId = "d5b9ad05-d155-4c74-baee-1c2eb15bc98b",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "1d5e970e-e882-4262-9554-0834284478d1",
                            Name = "MVC: Lesson 1",
                            Order = 0,
                            SectionId = "807548ea-cef2-4a58-a889-7e7bb133e963",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "b29da32b-f014-44f4-96cd-13a9b9e17688",
                            Name = "MVC: Lesson 2",
                            Order = 0,
                            SectionId = "807548ea-cef2-4a58-a889-7e7bb133e963",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "31860ce5-81b4-407c-8189-682ecf94883e",
                            Name = "MVC: Lesson 3",
                            Order = 0,
                            SectionId = "807548ea-cef2-4a58-a889-7e7bb133e963",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "95684232-976d-42a9-aea9-2971fb1a9a90",
                            Name = "MVC: Lesson 4",
                            Order = 0,
                            SectionId = "807548ea-cef2-4a58-a889-7e7bb133e963",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "b0abf9c9-c702-4561-8387-6f80e76100c2",
                            Name = "MVC: Lesson 5",
                            Order = 0,
                            SectionId = "807548ea-cef2-4a58-a889-7e7bb133e963",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "01c795f5-e89f-4b36-8e06-355a7ff48acd",
                            Name = "MVC: Lesson 6",
                            Order = 0,
                            SectionId = "807548ea-cef2-4a58-a889-7e7bb133e963",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "604cc026-c1e0-492c-a1e1-820440e995fc",
                            Name = "MVC: Lesson 7",
                            Order = 0,
                            SectionId = "807548ea-cef2-4a58-a889-7e7bb133e963",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "76e61d53-300b-450b-ac0f-eb9f93ecacca",
                            Name = "MVC: Lesson 8",
                            Order = 0,
                            SectionId = "807548ea-cef2-4a58-a889-7e7bb133e963",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "7d34115e-e389-4f17-a9f8-182519e4c104",
                            Name = "MVC: Lesson 9",
                            Order = 0,
                            SectionId = "807548ea-cef2-4a58-a889-7e7bb133e963",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "949795f4-5baa-4fa9-b13a-7b9208c731b6",
                            Name = "MVC: Lesson 10",
                            Order = 0,
                            SectionId = "807548ea-cef2-4a58-a889-7e7bb133e963",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "300baf6a-2840-43dc-8d11-42b74852db9e",
                            Name = "Entity Framework: Lesson 1",
                            Order = 0,
                            SectionId = "8b2245cd-7979-452b-96b5-f7e8ab40b83e",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "77ee978e-d135-44b1-9127-b8e39340e07e",
                            Name = "Entity Framework: Lesson 2",
                            Order = 0,
                            SectionId = "8b2245cd-7979-452b-96b5-f7e8ab40b83e",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "f1632cce-d548-4dfb-bd67-52121eefbb33",
                            Name = "Entity Framework: Lesson 3",
                            Order = 0,
                            SectionId = "8b2245cd-7979-452b-96b5-f7e8ab40b83e",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "c8740a34-e786-429a-a949-5a069ab4d1d7",
                            Name = "Entity Framework: Lesson 4",
                            Order = 0,
                            SectionId = "8b2245cd-7979-452b-96b5-f7e8ab40b83e",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "d10c2413-45c7-4ba5-a918-3635690efd3b",
                            Name = "Entity Framework: Lesson 5",
                            Order = 0,
                            SectionId = "8b2245cd-7979-452b-96b5-f7e8ab40b83e",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "727a7c6e-b346-4c6b-86a5-94f4e0dd8987",
                            Name = "Entity Framework: Lesson 6",
                            Order = 0,
                            SectionId = "8b2245cd-7979-452b-96b5-f7e8ab40b83e",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "04d642c3-4c5a-4b7a-af97-1d4464da9fc4",
                            Name = "Entity Framework: Lesson 7",
                            Order = 0,
                            SectionId = "8b2245cd-7979-452b-96b5-f7e8ab40b83e",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "f3eb5053-905d-4e00-b239-f037348de458",
                            Name = "Entity Framework: Lesson 8",
                            Order = 0,
                            SectionId = "8b2245cd-7979-452b-96b5-f7e8ab40b83e",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "8ba324b4-0d8b-4bfe-a305-6b5dc3d86734",
                            Name = "Entity Framework: Lesson 9",
                            Order = 0,
                            SectionId = "8b2245cd-7979-452b-96b5-f7e8ab40b83e",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "1b7fa50c-9e19-46be-a023-818efc72c3fb",
                            Name = "Entity Framework: Lesson 10",
                            Order = 0,
                            SectionId = "8b2245cd-7979-452b-96b5-f7e8ab40b83e",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "24517c22-378d-42c0-830e-72d7c41fde17",
                            Name = "Entity Framework: Lesson 11",
                            Order = 0,
                            SectionId = "8b2245cd-7979-452b-96b5-f7e8ab40b83e",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "62d321d0-a42f-46d2-8796-7ccb315edd57",
                            Name = "Entity Framework: Lesson 12",
                            Order = 0,
                            SectionId = "8b2245cd-7979-452b-96b5-f7e8ab40b83e",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "796f7615-1135-4084-acc4-c6e1e8f27dc1",
                            Name = "Entity Framework: Lesson 13",
                            Order = 0,
                            SectionId = "8b2245cd-7979-452b-96b5-f7e8ab40b83e",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "fed8cd74-afb4-4b2d-8e19-bebf2bea43b9",
                            Name = "Entity Framework: Lesson 14",
                            Order = 0,
                            SectionId = "8b2245cd-7979-452b-96b5-f7e8ab40b83e",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "0aced6cd-ff98-4964-90a9-b690e8c97915",
                            Name = "Entity Framework: Lesson 15",
                            Order = 0,
                            SectionId = "8b2245cd-7979-452b-96b5-f7e8ab40b83e",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "33634191-15d7-47c6-a631-aa174e60460d",
                            Name = "Entity Framework: Lesson 16",
                            Order = 0,
                            SectionId = "8b2245cd-7979-452b-96b5-f7e8ab40b83e",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "ee6fe37d-470d-4d1c-8e15-1be7312736c9",
                            Name = "Entity Framework: Lesson 17",
                            Order = 0,
                            SectionId = "8b2245cd-7979-452b-96b5-f7e8ab40b83e",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "c03d1e15-9e7f-4378-89f4-c121463f1938",
                            Name = "Entity Framework: Lesson 18",
                            Order = 0,
                            SectionId = "8b2245cd-7979-452b-96b5-f7e8ab40b83e",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "1a427c9a-4e62-45e6-b10f-358283c06453",
                            Name = "Entity Framework: Lesson 19",
                            Order = 0,
                            SectionId = "8b2245cd-7979-452b-96b5-f7e8ab40b83e",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "af9d8a0f-0523-4300-a45d-63d407eb5285",
                            Name = "Entity Framework: Lesson 20",
                            Order = 0,
                            SectionId = "8b2245cd-7979-452b-96b5-f7e8ab40b83e",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "3273ab28-61be-443f-90a2-50afe6628bd6",
                            Name = "Web API: Lesson 1",
                            Order = 0,
                            SectionId = "75a08717-d091-49bc-867c-2340f4c6d058",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "c57f32f1-33b3-4e30-9253-93c470d4bc2c",
                            Name = "Web API: Lesson 2",
                            Order = 0,
                            SectionId = "75a08717-d091-49bc-867c-2340f4c6d058",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "d6432df0-476d-4122-b086-1f90c756b8dc",
                            Name = "Web API: Lesson 3",
                            Order = 0,
                            SectionId = "75a08717-d091-49bc-867c-2340f4c6d058",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "70775f5b-3257-4739-b022-16098b16769e",
                            Name = "Web API: Lesson 4",
                            Order = 0,
                            SectionId = "75a08717-d091-49bc-867c-2340f4c6d058",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "fb23bf54-2ac6-4590-9f27-1387e49e525f",
                            Name = "Web API: Lesson 5",
                            Order = 0,
                            SectionId = "75a08717-d091-49bc-867c-2340f4c6d058",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "1b066bfd-2b3d-4de7-b8c4-254a087fb8d5",
                            Name = "Web API: Lesson 6",
                            Order = 0,
                            SectionId = "75a08717-d091-49bc-867c-2340f4c6d058",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "9b790b4e-ebb8-464c-b74c-b32550622f1e",
                            Name = "Web API: Lesson 7",
                            Order = 0,
                            SectionId = "75a08717-d091-49bc-867c-2340f4c6d058",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "7e5af8f8-9908-402b-9617-83d9e6e33ac7",
                            Name = "Web API: Lesson 8",
                            Order = 0,
                            SectionId = "75a08717-d091-49bc-867c-2340f4c6d058",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "eaf0c338-d84a-4bc7-9569-2a87fe8caeb3",
                            Name = "Web API: Lesson 9",
                            Order = 0,
                            SectionId = "75a08717-d091-49bc-867c-2340f4c6d058",
                            VideoUrl = ""
                        },
                        new
                        {
                            Id = "eb1b0884-a7d5-464e-92dc-1b3a51ed3cb5",
                            Name = "Web API: Lesson 10",
                            Order = 0,
                            SectionId = "75a08717-d091-49bc-867c-2340f4c6d058",
                            VideoUrl = ""
                        });
                });

            modelBuilder.Entity("API.Models.Section", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CourseId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Sections");

                    b.HasData(
                        new
                        {
                            Id = "8c628339-02b3-4546-9e3f-a3dfbbfa564c",
                            CourseId = "a945757a-fc5d-4558-a3f6-8716545ab954",
                            Name = "Routing",
                            Order = 0
                        },
                        new
                        {
                            Id = "a5f742ec-af3b-41d7-b938-3f4c0de86b06",
                            CourseId = "a945757a-fc5d-4558-a3f6-8716545ab954",
                            Name = "Service",
                            Order = 0
                        },
                        new
                        {
                            Id = "d5b9ad05-d155-4c74-baee-1c2eb15bc98b",
                            CourseId = "a945757a-fc5d-4558-a3f6-8716545ab954",
                            Name = "Directive",
                            Order = 0
                        },
                        new
                        {
                            Id = "807548ea-cef2-4a58-a889-7e7bb133e963",
                            CourseId = "befa383d-07d6-4b2b-aa57-8eea7132c4e5",
                            Name = "MVC",
                            Order = 0
                        },
                        new
                        {
                            Id = "8b2245cd-7979-452b-96b5-f7e8ab40b83e",
                            CourseId = "befa383d-07d6-4b2b-aa57-8eea7132c4e5",
                            Name = "Entity Framework",
                            Order = 0
                        },
                        new
                        {
                            Id = "75a08717-d091-49bc-867c-2340f4c6d058",
                            CourseId = "befa383d-07d6-4b2b-aa57-8eea7132c4e5",
                            Name = "Web API",
                            Order = 0
                        });
                });

            modelBuilder.Entity("API.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "7a1ddab6-59b9-449a-ae90-40701f9158ea",
                            FullName = "Leon",
                            ImageUrl = ""
                        });
                });

            modelBuilder.Entity("API.Models.WatchLog", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("CourseId")
                        .HasColumnType("text");

                    b.Property<string>("LessonId")
                        .HasColumnType("text");

                    b.Property<int>("PercentageWatched")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId");

                    b.ToTable("WatchLogs");
                });

            modelBuilder.Entity("API.Models.Lesson", b =>
                {
                    b.HasOne("API.Models.Section", "Section")
                        .WithMany("Lessons")
                        .HasForeignKey("SectionId");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("API.Models.Section", b =>
                {
                    b.HasOne("API.Models.Course", "Course")
                        .WithMany("Sections")
                        .HasForeignKey("CourseId");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("API.Models.WatchLog", b =>
                {
                    b.HasOne("API.Models.Lesson", "Lesson")
                        .WithMany("WatchLogs")
                        .HasForeignKey("LessonId");

                    b.HasOne("API.Models.User", "User")
                        .WithMany("WatchLogs")
                        .HasForeignKey("UserId");

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Models.Course", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("API.Models.Lesson", b =>
                {
                    b.Navigation("WatchLogs");
                });

            modelBuilder.Entity("API.Models.Section", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("API.Models.User", b =>
                {
                    b.Navigation("WatchLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
